### PR TITLE
Skip symlink dependencies in build

### PR DESCRIPTION
**Pull request by kimjoar**
Preparing for the use of `link:` dependencies, see https://github.com/elastic/kibana/issues/14993.

EDIT: This can now be tested together with https://github.com/elastic/x-pack-kibana/pull/4505

Here's an example of a minimal Kibana plugin ([my-kbn-plugin-0.0.0.zip](https://github.com/elastic/kibana/files/1703001/my-kbn-plugin-0.0.0.zip)) that I built using this change.

To test the example package, first build Kibana (`yarn build --skip-archives --skip-os-packages`), then cd into `build/kibana-...` for your architecture, then run:

```
./bin/kibana-plugin install file:./path/to/my-kbn-plugin-0.0.0.zip
```

and you should see something like this in the output when starting the Kibana server:

```
{ units: [ 'y', 'M', 'w', 'd', 'h', 'm', 's', 'ms' ] }
```

(you'll see it during optimize after plugin install, as optimize starts the kibana server)

You should see this when starting up on server, when the api endpoint is hit, and when opening the plugin in the ui.

### CODE REVIEW

**Comment by w33ble** [comment]
> This is a fork of gulp-zip

What are the chances of a proper repo fork here, instead of just copying code into this repo?

**Comment by kimjoar** [comment]
I expect we'll move back as soon as gulp as updated all its things. Any pros to forking a repo and publishing a version vs just inlining the code while we wait for an upgrade? I usually favour the latter, as it seems much simpler (especially when it's just a small function like this)

**Comment by w33ble** [comment]
> Any pros to forking a repo and publishing a version vs just inlining the code while we wait for an upgrade?

It's a lot clearer what was actually changed from the upstream library. I have no idea what, if anything, you changed here.

As an added bonus, it becomes a one line change in the package.json instead of having to go back and revert this PR. 

IMO, forking *should* be a bunch of work, it's a last resort.

**Comment by w33ble** [comment]
> Preparing for the use of link: dependencies.

A description or a link to the parent change/PR would be helpful. What are "`link:` dependencies"?

**Comment by kimjoar** [comment]
Btw, I'll prepare a proper test-case for this stuff, so this can wait until after the `kibana-extra` stuff

**Comment by w33ble** [comment]
`gulp-zip` was updated in #61... do you still need that change in this pr?

**Comment by kimjoar** [comment]
@w33ble :+1: Awesome, will move back to `gulp-zip`.

**Comment by kimjoar** [comment]
I've pushed https://github.com/elastic/x-pack-kibana/pull/4505 which can be used to test this process.

**Comment by kimjoar** [comment]
@w33ble @spalger I've updated the description, want to take a look at this?

**Comment by kimjoar** [comment]
(Btw, instead of updating the `package.json` before installing deps, and then updating it again after to add back `link:` deps in `dependencies`, I went with this approach as it felt "simpler". Either approach would be okey with me, though.)

**Review by spalger — APPROVED** [review]
LGTM

**Comment by spalger** [comment]
@w33ble you good with this?

**Review by w33ble — APPROVED** [review]
(༎ິ῀̫ ༎ິ ̨ )͞˭̳̳̳˭̳̳̳ˍ̿̿ˍ̿ˌ˳ˏ̇⋅∴༣

**Comment by kimjoar** [comment]
Closing, see https://github.com/elastic/kibana/pull/16727

**Pull request closed without merging**
