### PR TITLE
mention new bundled plugin helpers

### PR DESCRIPTION
**Pull request by spalger**
Updates the readme to point people targeting 6.3+ to the bundled plugin helpers.

### CODE REVIEW

**Review by w33ble — APPROVED** [review]
😋

**Review by kimjoar — APPROVED** [review]
❤️

**Comment by w33ble** [comment]
@spalger we should probably deprecate 8.x and 9.x on npm too, yeah?

**Comment by spalger** [comment]
Good call, just deprecated 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 9.0.0, 9.0.1, and 9.0.2

**Pull request merged**
