### PR TITLE
Remove kibanaRoot option, require kibana-extra

### PR DESCRIPTION
**Pull request by kimjoar**
Part of https://github.com/elastic/kibana/issues/15452.

### CODE REVIEW

**Comment by w33ble** [comment]
Any plans for deprecating the `kibanaPath` setting? This is going to be another major version change, which is fine, but it would be nice to alert plugin developers to the upcoming path requirements. I'm thinking just some kind of message that explains the upstream changes that are coming, and maybe provides a url to https://github.com/elastic/kibana/issues/14993 as a reference... thoughts? 

EDIT: What I mean by deprecating the setting is letting developers know in the current version(s) of the plugin that the setting will be going away, so it's not a surprise in the future when they upgrade and that setting causes the process to throw.

**Comment by kimjoar** [comment]
++ to deprecating. I can add a separate PR for it.

Btw, I added a postinstall check in https://github.com/elastic/kibana-plugin-helpers/pull/58/commits/497559ddc83aa2ca2108bb998712426a30696c1c. Does that make sense? (https://github.com/elastic/template-kibana-plugin/blob/master/template/package.json#L16 seems to have been unused so far, so no necessary changes there)

**Comment by w33ble** [comment]
Makes sense. Fix your lint issues though ;).

**Comment by kimjoar** [comment]
🔥

**Review by w33ble — APPROVED** [review]
LGTM

**Comment by w33ble** [comment]
@kjbekkelund Remember to cut a new major version when you publish this.

I'd also really appreciate a new PR with a deprecation message about `kibanaPath` before you merge this. I'll settle for an issue about adding a deprecation notice in 8.x if you don't have time though.

**Pull request merged**
