### PR TITLE
[test:server] fall-back to babel/register script if mocha_setup not available

### LINKED ISSUE #67: task 'test:server' failed after upgrade to Kibana 5.6.7
Hello,

Context: I'm migrating custom Kibana plugins from Kibana 5.2.2 to Kibana 5.6.7.
I updated my `package.json`, upgraded my code, tested with `npm run start` and everything is fine.
I'm using now "@elastic/plugin-helpers": "8.1.3" which seems to be the latest version compatible with my setup.
I did not run the "template-kibana-plugin" again to do this migration.

What's happening: `npm run test:server` fails with following error:

```
Error: Cannot find module 'D:\Users\xxxxxx\src\kibana\test\mocha_setup.js'
```

My understanding: the thing is that `mocha_setup.js` does not belong to Kibana 5.6.7 anymore. It seems that there were plans to move scripts ([kibana#11095](https://github.com/elastic/kibana/issues/11095)) with impacts on makelogs and mocha npm scripts ([kibana #11665](https://github.com/elastic/kibana/pull/11665)) which were backported to 5.x.
Plugin Helpers still reference this `mocha_setup.js` script in this version ([link](https://github.com/elastic/kibana-plugin-helpers/blob/master/tasks/test/server/test_server_action.js#L9): 
```js
const mochaSetupJs = resolve(plugin.kibanaRoot, 'test/mocha_setup.js');
```
I think the `test_server_action.js` file needs a patch.

I know my setup is deprecated, but is there any chance that this gets fixed? Any idea of a workaround?

### PR DESCRIPTION
**Pull request by spalger**
Fixes #67 

When https://github.com/elastic/kibana/pull/15281 was backported to kibana 5.6 it removed the `mocha_setup.js` script that the test:server task was using, but all it really did was load the babel-register script, so we do that if the mocha_setup script is not available.

Will need to backport to 6.x too I think.

### CODE REVIEW

**Comment by w33ble** [comment]
I tried this by downloading Kibana 5.6.7, using the template to make a new plugin, and then linking to your code.

```
# fetch and link PR code
$ git clone --branch 7.x git@github.com:spalger/kibana-plugin-helpers.git
$ cd kibana-plugin-helpers && yarn install && yarn link && cd ..

$ git clone --branch 5.6 git@github.com:elastic/kibana.git --depth 1
$ cd kibana && yarn install && cd ..

$ sao -u elastic/template-kibana-plugin#7.x test-plugin
# selected yes for all options
$ cd test-plugin && yarn install && yarn link @elastic/plugin-helpers

$ yarn run test:server
yarn run v1.3.2
warning package.json: No license field
$ plugin-helpers test:server


  suite
    ✓ is a test


  1 passing (12ms)

✨  Done in 1.93s.

**Review by w33ble — APPROVED** [review]

**Comment by w33ble** [comment]
Oh, I should note that I get the error from #67 if I don't use the link:

> Error: Cannot find module '/Users/d33t/repos/test/kibana/test/mocha_setup.js'

**Comment by spalger** [comment]
Backported to 6.x in 4bc6eb1

**Comment by w33ble** [comment]
@spalger thanks. I'm was planning on treating 6.x as deprecated at this point. I don't think we have any supported versions of Kibana that run on an older version of node than v6, which was the breaking change in v7 of the plugin helpers. Am I wrong?

- [4.6 requires v6](https://github.com/elastic/kibana/blob/4.6/.node-version)
- [5.0+ requires v6](https://github.com/elastic/kibana/blob/5.0/.node-version)
- [6.0+ requires v6](https://github.com/elastic/kibana/blob/6.0/.node-version)

**Comment by spalger** [comment]
I'm not 100% certain, but that sounds right. I just backported because it was listed in the README.

**Pull request merged**
